plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'com.effects.audio'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.slf4j:slf4j-api:$slf4j_version"
    implementation "ch.qos.logback:logback-classic:$logback_version"
    implementation 'com.googlecode.soundlibs:mp3spi:1.9.5.4'      // MP3 decoding
    implementation 'com.googlecode.soundlibs:tritonus-share:0.3.7.4' // library for mp3spi
}

javafx {
    version = '26'
    modules = ['javafx.controls']
}

application {
    mainClass = 'effects.audio.Main'
}

jar {
    archiveBaseName = "${archivesName}-${version}"

    manifest {
        attributes(
                'Main-Class': application.mainClass.get()
        )
    }
}

shadowJar {
    archiveFileName = "${archivesName}-${version}.jar"
    exclude 'module-info.class'
    exclude 'javafx/**'
    exclude 'com/sun/javafx/**'
    exclude 'com/sun/glass/**'
    exclude 'com/sun/prism/**'
}

// jpackage task
tasks.register('jpackage', Exec) {
    dependsOn shadowJar

    File outputDir = layout.projectDirectory.dir('installer').asFile
    File inputDir = layout.buildDirectory.dir('libs').get().asFile
    String jarName = "${archivesName}-${version}.jar"
    String iconPath = 'src/main/resources/sprites/icon.ico'

    doFirst {
        outputDir.mkdirs()
        delete fileTree(outputDir) {
            include '*.exe'
        }
    }

    commandLine 'jpackage',
            '--type',         'exe',
            '--name',         'Audio Effects',
            '--app-version',  '1.0',
            '--input',        inputDir.absolutePath,
            '--main-jar',     jarName,
            '--main-class',   application.mainClass.get(),
            '--dest',         outputDir.absolutePath,
            '--icon',         iconPath,
            '--win-menu',
            '--win-shortcut-prompt',
            '--vendor',      'ItsNukea'
}

shadowJar.finalizedBy jpackage

test {
    useJUnitPlatform()
}