plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'com.effects.audio'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.slf4j:slf4j-api:$slf4j_version"
    implementation "ch.qos.logback:logback-classic:$logback_version"
}

application {
    mainClass = 'effects.audio.Main'
}

jar {
    archiveBaseName = "${archivesName}-${version}"

    manifest {
        attributes(
                'Main-Class': application.mainClass.get()
        )
    }
}

shadowJar {
    archiveFileName = "${archivesName}-${version}.jar"
}

// jpackage task
tasks.register('jpackage', Exec) {
    dependsOn shadowJar

    File outputDir = layout.buildDirectory.dir('installer').get().asFile
    File inputDir = layout.buildDirectory.dir('libs').get().asFile
    String jarName = "${archivesName}-${version}.jar"
    String iconPath = 'src/main/resources/sprites/icon.ico'

    doFirst {
        outputDir.mkdirs()
    }

    commandLine 'jpackage',
            '--type',         'exe',
            '--name',         'Audio Effects',
            '--app-version',  '1.0',
            '--input',        inputDir.absolutePath,
            '--main-jar',     jarName,
            '--main-class',   application.mainClass.get(),
            '--dest',         outputDir.absolutePath,
            '--icon',         iconPath,
            '--win-menu',
            '--win-shortcut',
            '--vendor',      'ItsNukea'

}

shadowJar.finalizedBy jpackage

test {
    useJUnitPlatform()
}

javafx {
    version = '25'
    modules = [ 'javafx.controls' ]
}