plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'com.effects.audio'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.slf4j:slf4j-api:$slf4j_version"
    implementation "ch.qos.logback:logback-classic:$logback_version"
}

application {
    mainClass = 'effects.audio.Main'
}

jar {
    archiveBaseName = "${archivesName}"

    manifest {
        attributes(
                'Main-Class': application.mainClass.get()
        )
    }
}

shadowJar {
    archiveFileName = "${archivesName}.jar"
}

tasks.register('copyJar', Copy) {
    dependsOn shadowJar

    from shadowJar.archiveFile
    into layout.projectDirectory.dir("downloads")
}

shadowJar.finalizedBy copyJar

test {
    useJUnitPlatform()
}

javafx {
    version = '25'
    modules = [ 'javafx.controls' ]
}